#version 460

layout(constant_id = 0) const uint thread_num = 64;
layout(local_size_y_id = 0) in;

// outB := alpha*A + B
layout(set=0, binding=0) readonly restrict buffer tensor_a{float a[];};
layout(set=0, binding=1) readonly restrict buffer tensor_b{float b[];};
layout(set=0, binding=2) writeonly restrict buffer tensor_out_b{float out_b[];};
layout( push_constant ) uniform constants {
    uint b;
    uint n;
    float alpha;
    uint a_b_stride;
    uint a_n_stride;
    uint b_b_stride;
    uint b_n_stride;
    uint out_b_b_stride;
    uint out_b_n_stride;
} args;

uint get_a_idx(uint b, uint n){
    return b * args.a_b_stride + n * args.a_n_stride;
}
uint get_b_idx(uint b, uint n){
    return b * args.b_b_stride + n * args.b_n_stride;
}
uint get_out_b_idx(uint b, uint n){
    return b * args.out_b_b_stride + n * args.out_b_n_stride;
}

void main(){
    const uint bi = gl_GlobalInvocationID.x;
    const uint i = gl_GlobalInvocationID.y;
    if(i < args.n){
        out_b[get_out_b_idx(bi,i)] =
            fma(args.alpha, a[get_a_idx(bi,i)], b[get_b_idx(bi,i)]);
    }
}
