#version 460

layout(local_size_x = 64) in;
layout(constant_id=0) const uint vector_size = 1;
layout(constant_id=1) const float alpha = 0.0;

// B := alpha*A + B
layout(set=0, binding=0) readonly restrict buffer tensor_a{float a[];};
layout(set=0, binding=1) buffer restrict tensor_b{float b[];};

void main(){
    const uint total_threads = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    const uint vidx = gl_GlobalInvocationID.x;
    for(uint i=vidx; i < vector_size; i+= total_threads){
        b[vidx] = fma(alpha, a[vidx], b[vidx]);
    }
}