#version 460

layout(constant_id = 0) const uint thread_num = 64;
layout(local_size_x_id = 0) in;

// B := alpha*A + B
layout(set=0, binding=0) readonly restrict buffer tensor_a{float a[];};
layout(set=0, binding=1) buffer restrict tensor_b{float b[];};
layout( push_constant ) uniform constants {
    uint vector_size;
    float alpha;
} args;

void main(){
    const uint vidx = gl_GlobalInvocationID.x;
    if(vidx < args.vector_size){
        b[vidx] = fma(args.alpha, a[vidx], b[vidx]);
    }
}