#version 460

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_shuffle : require
#extension GL_KHR_shader_subgroup_ballot: enable
#extension GL_KHR_shader_subgroup_arithmetic: enable

#define TILE_SIZE 4

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE) in;

layout(constant_id=0) const uint batch = 0;
layout(constant_id=1) const uint m = 0;
layout(constant_id=2) const uint n = 0;
layout(constant_id=3) const uint p = 0;
layout(constant_id=4) const float alpha = 0.0;
layout(constant_id=5) const float beta = 0.0;
layout(constant_id=6) const uint flags = 0x0;

const bool is_a_transposed = bool(flags & 0x1);
const bool is_b_transposed = bool(flags & 0x2);
const bool is_c_transposed = bool(flags & 0x4);

const uint a_size = m * n;
const uint b_size = n * p;
const uint c_size = m * p;

const uint tiled_a_rowcnt = (m / TILE_SIZE) + (m % TILE_SIZE == 0 ? 0 : 1);
const uint tiled_a_colcnt = (n / TILE_SIZE) + (n % TILE_SIZE == 0 ? 0 : 1);

// Note that If tile was R*C in A, then C*R in B.
const uint tiled_b_rowcnt = (n / TILE_SIZE) + (n % TILE_SIZE == 0 ? 0 : 1); // == tiled_a_colcnt
const uint tiled_b_colcnt = (p / TILE_SIZE) + (p % TILE_SIZE == 0 ? 0 : 1);

// c := alpha * A * B + beta * C
layout(set=0, binding=0) readonly restrict buffer tensor_a{float a[];};
layout(set=0, binding=1) readonly restrict buffer tensor_b{float b[];};
layout(set=0, binding=2) restrict buffer tensor_c{float c[];};

uint get_a_idx(uint batch, uint r, uint c, bool is_transposed){
    if(is_transposed){
        //Transposed(Column-major)
        return (batch * a_size) + (c * m) + r;
    } else{
        //Not transposed(Row-major)
        return (batch * a_size) + (r * n) + c;
    }
}
uint get_b_idx(uint batch, uint r, uint c, bool is_transposed){
    if(is_transposed){
        //Transposed(Column-major)
        return (batch * b_size) + (c * n) + r;
    } else {
        //Not transposed(Row-major)
        return (batch * b_size) + (r * p) + c;
    }
}
uint get_c_idx(uint batch, uint r, uint c, bool is_transposed){
    if(is_transposed){
        //Transposed(Column-major)
        return (batch * c_size) + (c * m) + r;
    } else {
        //Not transposed(Row-major)
        return (batch * c_size) + (r * p) + c;
    }
}

void main(){
    uint batchId = gl_WorkGroupID.x;
    uint tileRid = gl_WorkGroupID.y;
    uint tileCid = gl_WorkGroupID.z;

    float local_acc = 0.0f;
    // Each workgroup is responsible for 8*8 tile.
    for(int i=0; i<tiled_a_colcnt; i++){
        // Load each tile.
        float a_val = 0.0f;
        float b_val = 0.0f;
        // Load A tile (A reads through columns)
        const uint a_r = tileRid * TILE_SIZE + gl_LocalInvocationID.x;
        const uint a_c = i * TILE_SIZE + gl_LocalInvocationID.y;
        const uint b_r = i * TILE_SIZE + gl_LocalInvocationID.x;
        const uint b_c = tileCid * TILE_SIZE + gl_LocalInvocationID.y;
        if(a_r < m && a_c < n){
            a_val = a[get_a_idx(batchId, a_r, a_c, is_a_transposed)];
        }
        // Load B tile (B reads through rows)
        if(b_r < n && b_c < p){
            b_val = b[get_b_idx(batchId, b_r, b_c, is_b_transposed)];
        }

        // Calculate dot product for its local value.
        float dot_prod = 0.0f;
        for(int j = 0; j<TILE_SIZE; j++){
            //Subgroup에서는 zyx 순...
            uint da_idx = uint(j * TILE_SIZE + gl_LocalInvocationID.x);
            uint db_idx = uint(gl_LocalInvocationID.y * TILE_SIZE + j);

            float da = subgroupShuffle(a_val, da_idx);
            float db = subgroupShuffle(b_val, db_idx);
            dot_prod += da * db;
        }
        // Save each element in 'local_acc'
        local_acc += dot_prod;
    }
    // Add C and save it to C
    uint c_r = tileRid * TILE_SIZE + gl_LocalInvocationID.x;
    uint c_c = tileCid * TILE_SIZE + gl_LocalInvocationID.y;
    uint c_idx = get_c_idx(batchId, c_r, c_c, is_c_transposed);
    if(c_r < m && c_c < p){
        const float v = fma(alpha, local_acc, beta * c[c_idx]);
        c[c_idx] = v;
    }
}