#version 460

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_shuffle : require
#extension GL_KHR_shader_subgroup_ballot: enable
#extension GL_KHR_shader_subgroup_arithmetic: enable

#define TILE_M 8
#define TILE_N 4
#define TILE_K 4
// TILE_K <= TILE_N
// TILE_M * TILE_N == 32 assumed.
layout(local_size_x = TILE_M, local_size_y = TILE_N, local_size_z = 1) in;

layout(constant_id = 0) const uint batch = 0;
layout(constant_id = 1) const uint m = 0; // A rows, C rows
layout(constant_id = 2) const uint n = 0; // A cols, B rows, K
layout(constant_id = 3) const uint p = 0; // B cols, C cols
layout(constant_id = 4) const float alpha = 0.0;
layout(constant_id = 5) const float beta = 0.0;

const uint a_size = m * n;
const uint b_size = n * p;
const uint c_size = m * p;

const uint tiled_m_cnt = (m / TILE_M) + (m % TILE_M == 0 ? 0 : 1);
const uint tiled_k_cnt = (n / TILE_K) + (n % TILE_K == 0 ? 0 : 1);
const uint tiled_n_cnt = (p / TILE_N) + (p % TILE_N == 0 ? 0 : 1);

// c := alpha * A * B + beta * C
layout(set = 0, binding = 0) readonly restrict buffer tensor_a {
    float a[];
};

layout(set = 0, binding = 1) readonly restrict buffer tensor_b {
    float b[];
};

layout(set = 0, binding = 2) restrict buffer tensor_c {
    float c[];
};

uint get_a_idx(uint batch_id, uint r, uint col) {
    return (batch_id * a_size) + (r * n) + col;
}

uint get_b_idx(uint batch_id, uint r, uint col) {
    return (batch_id * b_size) + (r * p) + col;
}

uint get_c_idx(uint batch_id, uint r, uint col) {
    return (batch_id * c_size) + (r * p) + col;
}

void main() {
    const uint batch_id = gl_WorkGroupID.x;
    const uint tile_m_id = gl_WorkGroupID.y;
    const uint tile_n_id = gl_WorkGroupID.z;

    const uint local_m = gl_LocalInvocationID.x; // 0 .. TILE_M - 1
    const uint local_n = gl_LocalInvocationID.y; // 0 .. TILE_N - 1

    const uint global_m = tile_m_id * TILE_M + local_m;
    const uint global_n = tile_n_id * TILE_N + local_n;

    float acc = 0.0;

    for (uint tile_k_id = 0; tile_k_id < tiled_k_cnt; tile_k_id++) {
        float a_val = 0.0;
        float b_val = 0.0;

        // A tile: TILE_M x TILE_K
        //
        // Lane (local_m, local_n) loads A[local_m, local_n]
        // only when local_n < TILE_K.
        const uint a_r = global_m;
        const uint a_c = tile_k_id * TILE_K + local_n;

        if (local_n < TILE_K && a_r < m && a_c < n) {
            a_val = a[get_a_idx(batch_id, a_r, a_c)];
        }

        // B tile: TILE_K x TILE_N
        //
        // Lane (local_m, local_n) loads B[local_m, local_n]
        // only when local_m < TILE_K.
        const uint b_r = tile_k_id * TILE_K + local_m;
        const uint b_c = global_n;

        if (local_m < TILE_K && b_r < n && b_c < p) {
            b_val = b[get_b_idx(batch_id, b_r, b_c)];
        }

        // Dot product for C[global_m, global_n].
        for (uint k = 0; k < TILE_K; k++) {
            // Flattened local invocation index:
            // index = x + y * TILE_M
            //
            // A[local_m, k] is held by lane (local_m, k).
            const uint a_lane = local_m + k * TILE_M;

            // B[k, local_n] is held by lane (k, local_n).
            const uint b_lane = k + local_n * TILE_M;

            const float av = subgroupShuffle(a_val, a_lane);
            const float bv = subgroupShuffle(b_val, b_lane);

            acc += av * bv;
        }
    }

    if (global_m < m && global_n < p) {
        const uint c_idx = get_c_idx(batch_id, global_m, global_n);
        c[c_idx] = fma(alpha, acc, beta * c[c_idx]);
    }
}